
ARCHS?=i386 x86_64
ARCHOPTS=$(addprefix -arch ,$(ARCHS))

FRAMEWORKS=Foundation AppKit OpenGL

FLAGS=-D__MACOSX_CORE__ -I$(CK_SRC_PATH) $(ARCHOPTS) -fPIC
LDFLAGS=-bundle -lstdc++ $(ARCHOPTS) $(addprefix -framework ,$(FRAMEWORKS)) -ObjC \
-Wl,-undefined,dynamic_lookup

LD=clang++
CXX=clang++
