
OBJCXX_MODULES+=chugl_mac.mm

ARCHS?=i386 x86_64
ARCHOPTS=$(addprefix -arch ,$(ARCHS))

FRAMEWORKS=Foundation AppKit OpenGL ApplicationServices

FLAGS=-D__MACOSX_CORE__ -I$(CK_SRC_PATH) $(ARCHOPTS) -fPIC $(ISYSROOT)
LDFLAGS=-bundle $(ARCHOPTS) $(ISYSROOT) $(addprefix -framework ,$(FRAMEWORKS)) -ObjC \
-Wl,-undefined,dynamic_lookup

LD=clang++
CXX=clang++
OBJCXX=clang++

MACOSX_DEPLOYMENT_TARGET=10.5
export MACOSX_DEPLOYMENT_TARGET
